# Generated by Django 5.1.6 on 2025-03-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vip_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vvip_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotion_terms', models.TextField(blank=True, null=True)),
                ('promotion_message', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(upload_to='event_banners/')),
            ],
        ),
    ]
