# Generated by Django 5.1.6 on 2025-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_datetime_event_date_time_alter_event_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('ticket_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('recipients', models.TextField(help_text='Comma-separated list of recipient numbers')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer_contact', models.CharField(max_length=15)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_number', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
