# Generated by Django 5.1.6 on 2025-04-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
