# Generated by Django 5.1.6 on 2025-04-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_payment_buyer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(max_length=15)),
                ('ticket_type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='home.payment')),
            ],
        ),
    ]
