# Generated by Django 5.1.6 on 2025-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
