# Generated by Django 5.1.6 on 2025-05-02 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 2, 18, 3, 31, 928109, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipients',
            field=models.TextField(help_text='Comma-separated list of recipient emails'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='recipient_email',
            field=models.EmailField(max_length=254),
        ),
    ]
